server:
  port: 8001

spring:
  application:
    name: service-user
  profiles:
    active: dev
  # PostgreSQL 数据源（连接 Ubuntu 服务器，库 ms_ds_user）
  datasource:
    url: jdbc:postgresql://192.168.0.27:5432/ms_ds_user
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
  cloud:
    nacos:
      server-addr: 192.168.0.27:8848
      discovery:
        namespace: public
        username: nacos
        password: nacos
      config:
        import-check:
          enabled: false

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto

logging:
  level:
    com.ms.learn: debug
