server:
  port: 8000

spring:
  application:
    name: ms-gateway
  config:
    import:
      - optional:nacos:ms-gateway.yaml
  cloud:
    nacos:
      server-addr: 192.168.0.27:8848
      username: nacos
      password: nacos
      discovery:
        namespace: public
      config:
        namespace: public
        group: DEFAULT_GROUP
        file-extension: yaml
    gateway:
      routes:
        - id: service-user
          uri: lb://service-user
          predicates:
            - Path=/api/user/**
          filters:
            - StripPrefix=0
        - id: service-user-sso
          uri: lb://service-user
          predicates:
            - Path=/sso/**
          filters:
            - StripPrefix=0
        - id: service-order
          uri: lb://service-order
          predicates:
            - Path=/api/order/**
          filters:
            - StripPrefix=0
        - id: service-product
          uri: lb://service-product
          predicates:
            - Path=/api/product/**
          filters:
            - StripPrefix=0
        - id: service-transaction
          uri: lb://service-transaction
          predicates:
            - Path=/api/payment/**
          filters:
            - StripPrefix=0
        - id: service-points
          uri: lb://service-points
          predicates:
            - Path=/api/points/**
          filters:
            - StripPrefix=0
        - id: service-goods
          uri: lb://service-goods
          predicates:
            - Path=/api/goods/**
          filters:
            - StripPrefix=0
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowedOriginPatterns: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true

logging:
  level:
    org.springframework.cloud.gateway: debug
