server:
  port: 8080
demo:
  jwt:
    location: classpath:jwt.jks
    password: demo123
    alias: demo
    tokenTTL: 30m
  auth:
    excludePaths:
      - /search/**
      - /users/login
      - /item/**
      - /test