# cart-service
server:
  port: 9010

spring:
  application:
    name: cart-service
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.2.10:8848
  datasource:
    url: jdbc:mysql://${spring.database.mysql.host}:3306/test?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: hong
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  database:
    mysql:
      host: 192.168.2.10

mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: com.hong.domain
